dist: trusty
sudo: false

language: c++

compiler:
  - gcc

addons:
  apt:
    packages:
    - libelf-dev

env:
  - BUILD=RELEASE

install:
  - mkdir depends && cd depends
  - systemc=systemc-2.3.2
  - wget http://www.accellera.org/images/downloads/standards/systemc/$systemc.tar.gz
  - tar -xzf $systemc.tar.gz && cd $systemc
  - mkdir BUILD && cd BUILD
  - ../configure --enable-static
  - make && make install
  - cd ..
  - export SYSTEMC_HOME=`pwd`
  - export TARGET_ARCH=linux64
  - cd ..
  - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
  - tar -xzf release-1.8.0.tar.gz
  - cd googletest-release-1.8.0
  - mkdir BUILD && cd BUILD
  - cmake .. -DCMAKE_INSTALL_PREFIX=INSTALL
  - export GTEST_ROOT=`pwd`/INSTALL
  - export GMOCK_ROOT=$GTEST_ROOT
  - cd ../..


before_script:
  - mkdir BUILD && cd BUILD
  - cmake .. -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=$BUILD

script:
  - make && ctest --output-on-failure
